### ISSUE TITLE
npm run serve fails

### ISSUE THREAD

**Issue by wmww** [OpenStarscape/starscape-web#1]
I don't know exactly what it's supposed to do, so I haven't done even the tiniest amount of debugging. `npm install` seems to work. `npm run serve` gives me this:
```
wmww@wmwwXPS:~/code/games/open_starscape/openstarscape-web-client$ npm run serve
npm WARN npm npm does not support Node.js v10.17.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! path /home/wmww/code/games/open_starscape/openstarscape-web-client/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/wmww/code/games/open_starscape/openstarscape-web-client/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/wmww/.npm/_logs/2020-03-27T15_52_37_381Z-debug.log
```
EDIT: installing updates now in case that fixes any version related issues

**Comment by f-prime** [comment]
I should have specified in the README that those commands need to be run in the `openstarscape` subfolder which is where the actual project code is contained.

**Comment by wmww** [comment]
Hmm... it looks like Ubuntu 20.04 has a relatively modern Node.js but a 2 year old and incompatible npm. Will have to find another way to install npm. Such as turning on my Arch laptop.

**Comment by wmww** [comment]
None if this is relevant any more
